kind: pipeline
name: Build & Push 

steps:
- name: docker  
  image: plugins/docker
  tags:
  - ${DRONE_TAG}
  - latest
  settings:
    repo: str00bs/fediviz
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag
trigger:
  event:
  - tag

