kind: pipeline
name: Build & Push 

steps:
- name: Build & Push
  image: plugins/docker
  settings:
    repo: str00bs/fediviz
    tags:
    - ${DRONE_TAG}
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - tag

trigger:
  event:
  - tag

