services:
  fediviz:
    image: str00bs/fediviz:latest
    container_name: fediviz
    restart: unless-stopped
    networks:
      - fediviz-net
      - proxy
    environment:
      # Global
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=${ST_STREAMLIT_GLOBAL_DEVELOPMENT_MODE}
      # Server
      - STREAMLIT_SERVER_HOST=${ST_STREAMLIT_SERVER_HOST}
      - STREAMLIT_SERVER_PORT=${ST_STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=${ST_STREAMLIT_SERVER_MAX_UPLOAD_SIZE}
      - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=${ST_STREAMLIT_SERVER_ENABLE_STATIC_SERVING}
      # Browser
      - STREAMLIT_BROWSER_SERVER_ADDRESS=${ST_STREAMLIT_BROWSER_SERVER_ADDRESS}
      - STREAMLIT_BROWSER_SERVER_PORT=${ST_STREAMLIT_BROWSER_SERVER_PORT}
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=${ST_STREAMLIT_BROWSER_GATHER_USAGE_STATS}
      # Theme
      - STREAMLIT_THEME_BASE=${ST_STREAMLIT_THEME_BASE}
      - STREAMLIT_THEME_PRIMARY_COLOR=${ST_STREAMLIT_THEME_PRIMARY_COLOR}
      - STREAMLIT_THEME_BACKGROUND_COLOR=${ST_STREAMLIT_THEME_BACKGROUND_COLOR}
      - STREAMLIT_THEME_SECONDARY_BACKGROUND_COLOR=${ST_STREAMLIT_THEME_SECONDARY_BACKGROUND_COLOR}
      - STREAMLIT_THEME_TEXT_COLOR=${ST_STREAMLIT_THEME_TEXT_COLOR}
    labels:
      - traefik.enable=true
      # Routers
      - traefik.http.routers.fediviz.tls=true
      - traefik.http.routers.fediviz.tls.certresolver=letsencrypt
      - traefik.http.routers.fediviz.entrypoints=https
      - traefik.http.routers.fediviz.rule=Host(`${DOMAIN}`)
      # Services
      - traefik.http.services.fediviz.loadbalancer.server.port=80

networks:
  fediviz-net:
    name: fediviz-net
    external: false
  proxy:
    external: true
